language: node_js
sudo: required
services:
  - docker
node_js:
  - 10.16.3

env:
  global:
    - SHA=$(git rev-parse --short HEAD)

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Test
      script:
        - echo nothing
    - stage: Deploy
      if: type = push AND branch IN (master, production)
      install: true
      script: skip
      deploy:
        provider: script
        script: bash ./deploy.sh
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^production|master$
