FROM node:10.16.3
WORKDIR /app
COPY ./package.json yarn.lock ./
RUN yarn install --frozen-lockfile

ENV TZ=Australia/Sydney
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . .

EXPOSE 4100
CMD [ "yarn", "resque" ]
