exports.fields = {
  group_code: 'group_code',
  group_name: 'group_name',
  product_name: 'product_name',
  product_id: 'product_id',
  w2_rating_image: 'rating_image',
  w5_summary: 'summary',
  w6_performance: 'performance',
  w7_variety_option: 'variety_option',
  w8_process: 'process',
  w9_inv_score: 'inv_score',
  w10_small_account: 'small_account',
  w11_medium_account: 'medium_account',
  w12_large_account: 'large_account',
  w13_fee_score: 'fee_score',
  w14_death: 'death',
  w15_death_tpd: 'death_tpd',
  w16_income_protection: 'income_protection',
  w17_ins_score: 'ins_score',
  w18_member: 'member',
  w20_structure_service: 'structure_service',
  w21_service_score: 'service_score',
  w18a_advice: 'advice',
  f212_advice_roadsign: 'advice_roadsign',
  f213_governance: 'governance',
  f214_governance_roadsign: 'governance_roadsign',
  w23_membership: 'membership',
  w24_total_asset: 'total_asset',
  w25_startdate: 'startdate',
  w26_target_market: 'target_market',
  w27_public_offer: 'public_offer',
  w28_fund_type: 'fund_type',
  w29_what_we_say_fund_summary: 'what_we_say_fund_summary',
  w120_ins_whatwesay: 'ins_whatwesay',
  w53_intl_shares: 'intl_shares',
  w54_aus_shares: 'aus_shares',
  w55_property: 'property',
  w56_alternative: 'alternative',
  w57_fixed_interest: 'fixed_interest',
  w58_cash: 'cash',
  w59_other: 'other',
  w84_individual_shares: 'individual_shares',
  w84a_term_deposits: 'term_deposits',
  w100_basic_fee: 'basic_fee',
  w100a_basic_fee_5k: 'basic_fee_5k',
  w100b_basic_fee_100k: 'basic_fee_100k',
  w100c_basic_fee_250k: 'basic_fee_250k',
  w100d_basic_fee_500k: 'basic_fee_500k',
  w101_industry_avg_fee: 'industry_avg_fee',
  w101a_industry_avg_fee_5k: 'industry_avg_fee_5k',
  w101b_industry_avg_fee_100k: 'industry_avg_fee_100k',
  w91_member_fee: 'member_fee',
  w92_rnage_contribution_fee: 'rnage_contribution_fee',
  w93_withdrawal_fee: 'withdrawal_fee',
  w94_asset_admin_fee: 'asset_admin_fee',
  w95_investment_fee: 'investment_fee',
  w96_switching_fee: 'switching_fee',
  w97_trustee_fee: 'trustee_fee',
  w3_website: 'website',
  w4_phone_number: 'phone_number',
  w4a_analyst: 'analyst',
  w22_division: 'division',
  w30_valid_date: 'valid_date',
  w0_short_name: 'short_name',
  w1_fund_name: 'fund_name',
  w19_employer: 'employer',
  w118_default_option: 'default_option',
  w111_finplan_service: 'finplan_service',
  w112_health_insurance: 'health_insurance',
  w113_home_loans: 'home_loans',
  w114_webmemb_access: 'webmemb_access',
  w115_transaction: 'transaction',
  w116_halfyearreport: 'halfyearreport',
  w117_newsletter: 'newsletter',
  w119_credit_cards: 'credit_cards',
  w120a_valuation_process: 'valuation_process',
  w121_binding_nominations: 'binding_nominations',
  w122_non_lapsing_binding_noms: 'non_lapsing_binding_noms',
  w123_ins_life_event_increases: 'ins_life_event_increases',
  w124_ltip: 'ltip',
  w125_anti_detriment: 'anti_detriment',
  w126_commercial_relation: 'commercial_relation',
  w102_against_ind_avg: 'against_ind_avg',
  w102a_against_ind_avg_5k: 'against_ind_avg_5k',
  w102b_against_ind_avg_100k: 'against_ind_avg_100k',
  w98_empsize_discount: 'empsize_discount',
  w99_acctsize_discount: 'acctsize_discount',
  w83_single_mgr_option: 'single_mgr_option',
  f166a: 'performance_2016',
  f166b: 'performance_2016_industry_average',
  f167a: 'performance_2015',
  f167b: 'performance_2015_industry_average',
  f168a: 'performance_2014',
  f168b: 'performance_2014_industry_average',
  f169a: 'performance_2013',
  f169b: 'performance_2013_industry_average',
  f170a: 'performance_2012',
  f170b: 'performance_2012_industry_average',
  f171a: '5_year_annualised_performance',
}

exports.years = [2012, 2013, 2014, 2015, 2016]

exports.ratings = [
  { name: 'Platinum', score: 1, regx: new RegExp('platinum', 'i') },
  { name: 'Gold', score: 2, regx: new RegExp('(my)?gold', 'i') },
  { name: 'Silver', score: 3, regx: new RegExp('(my)?silver', 'i') },
  { name: 'Other', score: 4, regx: new RegExp('(my)?other', 'i') },
  { name: 'MySuper Platinum', score: 1, regx: new RegExp('myplat', 'i') },
  { name: 'MySuper Gold', score: 2, regx: new RegExp('mygold', 'i') },
  { name: 'MySuper Silver', score: 3, regx: new RegExp('mysilver', 'i') },
  { name: 'MySuper Other', score: 4, regx: new RegExp('myother', 'i') },
  { name: '5 Year Platinum Performance', score: 5, regx: new RegExp('5yr', 'i') },
  { name: '7 Year Platinum Performance', score: 6, regx: new RegExp('7yr', 'i') },
  { name: '10 Year Platinum Performance', score: 7, regx: new RegExp('10yr', 'i') },
  { name: 'Fund of the Year', score: 8, regx: new RegExp('(s)?foty', 'i') },
  { name: 'Super of the Year', score: 9, regx: new RegExp('sfoty', 'i') },
  { name: 'Super of the Year Finalist', score: 10, regx: new RegExp('sfoty_f', 'i') },
  { name: 'Pension of the Year', score: 11, regx: new RegExp('pfoty', 'i') },
  { name: 'Best New Innovation/Product', score: 12, regx: new RegExp('bnp', 'i') },
  { name: 'Best New Innovation/Product Finalist', score: 13, regx: new RegExp('bnp_f', 'i') },
  { name: 'Rising Star Award', score: 14, regx: new RegExp('rs', 'i') },
  { name: 'Rising Star Finalist', score: 15, regx: new RegExp('rs_f', 'i') },
  { name: 'Fast Mover', score: 16, regx: new RegExp('fm', 'i') },
  { name: 'SR50 Growth Index', score: 17, regx: new RegExp('50gr', 'i') },
  { name: 'SR50 Balanced Index', score: 18, regx: new RegExp('50bal', 'i') },
  { name: 'SR50 Capital Stable Index', score: 19, regx: new RegExp('50cap', 'i') },
  { name: 'SR50 Cash Index', score: 20, regx: new RegExp('50cash', 'i') },
  { name: 'SR50 Australian Shares Index', score: 21, regx: new RegExp('####', 'i') },
  { name: 'SR50 International Shares Index', score: 22, regx: new RegExp('50int', 'i') },
  { name: 'Infinity Award', score: 23, regx: new RegExp('infinity', 'i') },
  { name: 'Infinity Recognised', score: 24, regx: new RegExp('infinity_r', 'i') },
]

exports.segments = [
  { name: 'MySuper', regx: new RegExp('mysuper$', 'i') },
  { name: 'Personal', regx: new RegExp('(government|personal)$', 'i') },
  { name: 'Public Offer', regx: new RegExp('public offer$', 'i') },
  { name: 'Non Public Offer', regx: new RegExp('non public offer$', 'i') },
  { name: 'Account-based Pension', regx: new RegExp('pension$', 'i') },
  { name: 'Corporate', regx: new RegExp('corporate$', 'i') },
]

exports.purposes = [
  { name: 'Personal', regx: new RegExp('(industry-(mysuper|personal|public offer)|master trust-(mysuper|personal))', 'i') },
  { name: 'Other', regx: new RegExp('(corporate($|-mysuper|-personal)|government($|-mysuper|-personal)|industry-non public offer|master trust-corporate)', 'i') },
]
