exports.fields = {
  group_code: 'group_code',
  group_name: 'group_name',
  product_name: 'product_name',
  product_id: 'product_id',
  w2_rating_image: 'rating_image',
  w5_summary: 'summary',
  w6_performance: 'performance',
  w7_variety_option: 'variety_option',
  w8_process: 'process',
  w9_inv_score: 'inv_score',
  w10_small_account: 'small_account',
  w11_medium_account: 'medium_account',
  w12_large_account: 'large_account',
  w13_fee_score: 'fee_score',
  w14_death: 'death',
  w15_death_tpd: 'death_tpd',
  w16_income_protection: 'income_protection',
  w17_ins_score: 'ins_score',
  w18_member: 'member',
  w20_structure_service: 'structure_service',
  w21_service_score: 'service_score',
  w18a_advice: 'advice',
  f212_advice_roadsign: 'advice_roadsign',
  f213_governance: 'governance',
  f214_governance_roadsign: 'governance_roadsign',
  w23_membership: 'membership',
  w24_total_asset: 'total_asset',
  w25_startdate: 'startdate',
  w26_target_market: 'target_market',
  w27_public_offer: 'public_offer',
  w28_fund_type: 'fund_type',
  w29_what_we_say_fund_summary: 'what_we_say_fund_summary',
  w120_ins_whatwesay: 'ins_whatwesay',
  w53_intl_shares: 'intl_shares',
  w54_aus_shares: 'aus_shares',
  w55_property: 'property',
  w56_alternative: 'alternative',
  w57_fixed_interest: 'fixed_interest',
  w58_cash: 'cash',
  w59_other: 'other',
  w84_individual_shares: 'individual_shares',
  w84a_term_deposits: 'term_deposits',
  w100_basic_fee: 'basic_fee_50k',
  w100a_basic_fee_5_k: 'basic_fee_5k',
  w100b_basic_fee_100_k: 'basic_fee_100k',
  w100c_basic_fee_250_k: 'basic_fee_250k',
  w100d_basic_fee_500_k: 'basic_fee_500k',
  w101_industry_avg_fee: 'industry_avg_fee',
  w101a_industry_avg_fee_5_k: 'industry_avg_fee_5k',
  w101b_industry_avg_fee_100_k: 'industry_avg_fee_100k',
  w91_member_fee: 'member_fee',
  w92_rnage_contribution_fee: 'rnage_contribution_fee',
  w93_withdrawal_fee: 'withdrawal_fee',
  w94_asset_admin_fee: 'asset_admin_fee',
  w95a_icr_fee: 'indirect_cost_ratio',
  w95_investment_fee: 'investment_fee',
  w96_switching_fee: 'switching_fee',
  w97_trustee_fee: 'trustee_fee',
  w3_website: 'website',
  w4_phone_number: 'phone_number',
  w4a_analyst: 'analyst',
  w22_division: 'division',
  w30_valid_date: 'valid_date',
  w0_short_name: 'short_name',
  w1_fund_name: 'fund_name',
  w19_employer: 'employer',
  w118_default_option: 'default_option',
  w111_finplan_service: 'finplan_service',
  w112_health_insurance: 'health_insurance',
  w113_home_loans: 'home_loans',
  w114_webmemb_access: 'webmemb_access',
  w115_transaction: 'transaction',
  w116_halfyearreport: 'halfyearreport',
  w117_newsletter: 'newsletter',
  w119_credit_cards: 'credit_cards',
  w120a_valuation_process: 'valuation_process',
  w121_binding_nominations: 'binding_nominations',
  w122_non_lapsing_binding_noms: 'non_lapsing_binding_noms',
  w123_ins_life_event_increases: 'ins_life_event_increases',
  w124_ltip: 'ltip',
  w125_anti_detriment: 'anti_detriment',
  w126_commercial_relation: 'commercial_relation',
  w102_against_ind_avg: 'against_ind_avg',
  w102a_against_ind_avg_5_k: 'against_ind_avg_5k',
  w102b_against_ind_avg_100_k: 'against_ind_avg_100k',
  w98_empsize_discount: 'empsize_discount',
  w99_acctsize_discount: 'acctsize_discount',
  w83_single_mgr_option: 'single_mgr_option',
  w31_smart_fact1: 'pro_1',
  w32_smart_fact2: 'pro_2',
  w33_smart_fact3: 'pro_3',
  w34_smart_fact4: 'pro_4',
  w35_smart_fact5: 'pro_5',
  w36_smart_fact6: 'pro_6',
  w37_smart_fact7: 'pro_7',
  w38_smart_fact8: 'pro_8',
  w39_smart_fact9: 'pro_9',
  w40_smart_fact10: 'pro_10',
  w41_smart_fact11: 'pro_11',
  w42_smart_fact12: 'pro_12',
  f171a: '5_year_annualised_performance',
  f171b: '5_year_annualised_performance_avg',
  w43a_default: 'performance_balanced_fytd',
  w44a_option2: 'performance_balanced_fytd_avg',
  p_w44a_option2: 'performance_balanced_fytd_avg',
  f166a: 'performance_balanced_1',
  f166b: 'performance_balanced_1_avg',
  f167a: 'performance_balanced_2',
  f167b: 'performance_balanced_2_avg',
  f168a: 'performance_balanced_3',
  f168b: 'performance_balanced_3_avg',
  f169a: 'performance_balanced_4',
  f169b: 'performance_balanced_4_avg',
  f170a: 'performance_balanced_5',
  f170b: 'performance_balanced_5_avg',
  f177a: 'performance_high_growth_fytd',
  f177b: 'performance_high_growth_fytd_avg',
  f172a: 'performance_high_growth_1',
  f172b: 'performance_high_growth_1_avg',
  f173a: 'performance_high_growth_2',
  f173b: 'performance_high_growth_2_avg',
  f174a: 'performance_high_growth_3',
  f174b: 'performance_high_growth_3_avg',
  f175a: 'performance_high_growth_4',
  f175b: 'performance_high_growth_4_avg',
  f176a: 'performance_high_growth_5',
  f176b: 'performance_high_growth_5_avg',
  f183a: 'performance_conservative_balance_fytd',
  f183b: 'performance_conservative_balance_fytd_avg',
  f178a: 'performance_conservative_balance_1',
  f178b: 'performance_conservative_balance_1_avg',
  f179a: 'performance_conservative_balance_2',
  f179b: 'performance_conservative_balance_2_avg',
  f180a: 'performance_conservative_balance_3',
  f180b: 'performance_conservative_balance_3_avg',
  f181a: 'performance_conservative_balance_4',
  f181b: 'performance_conservative_balance_4_avg',
  f182a: 'performance_conservative_balance_5',
  f182b: 'performance_conservative_balance_5_avg',
  f189a: 'performance_secure_fytd',
  f189b: 'performance_secure_fytd_avg',
  f184a: 'performance_secure_1',
  f184b: 'performance_secure_1_avg',
  f185a: 'performance_secure_2',
  f185b: 'performance_secure_2_avg',
  f186a: 'performance_secure_3',
  f186b: 'performance_secure_3_avg',
  f187a: 'performance_secure_4',
  f187b: 'performance_secure_4_avg',
  f188a: 'performance_secure_5',
  f188b: 'performance_secure_5_avg',
  f195a: 'performance_diversified_fytd',
  f195b: 'performance_diversified_fytd_avg',
  f190a: 'performance_diversified_1',
  f190b: 'performance_diversified_1_avg',
  f191a: 'performance_diversified_2',
  f191b: 'performance_diversified_2_avg',
  f192a: 'performance_diversified_3',
  f192b: 'performance_diversified_3_avg',
  f193a: 'performance_diversified_4',
  f193b: 'performance_diversified_4_avg',
  f194a: 'performance_diversified_5',
  f194b: 'performance_diversified_5_avg',
  f126a: 'performance_growth_fytd',
  f126b: 'performance_growth_fytd_avg',
  f121a: 'performance_growth_1',
  f121b: 'performance_growth_1_avg',
  f122a: 'performance_growth_2',
  f122b: 'performance_growth_2_avg',
  f123a: 'performance_growth_3',
  f123b: 'performance_growth_3_avg',
  f124a: 'performance_growth_4',
  f124b: 'performance_growth_4_avg',
  f125a: 'performance_growth_5',
  f125b: 'performance_growth_5_avg',
  f132a: 'performance_aus_shares_fytd',
  f132b: 'performance_aus_shares_fytd_avg',
  f127a: 'performance_aus_shares_1',
  f127b: 'performance_aus_shares_1_avg',
  f128a: 'performance_aus_shares_2',
  f128b: 'performance_aus_shares_2_avg',
  f129a: 'performance_aus_shares_3',
  f129b: 'performance_aus_shares_3_avg',
  f130a: 'performance_aus_shares_4',
  f130b: 'performance_aus_shares_4_avg',
  f131a: 'performance_aus_shares_5',
  f131b: 'performance_aus_shares_5_avg',
  f138a: 'performance_intl_shares_fytd',
  f138b: 'performance_intl_shares_fytd_avg',
  f133a: 'performance_intl_shares_1',
  f133b: 'performance_intl_shares_1_avg',
  f134a: 'performance_intl_shares_2',
  f134b: 'performance_intl_shares_2_avg',
  f135a: 'performance_intl_shares_3',
  f135b: 'performance_intl_shares_3_avg',
  f136a: 'performance_intl_shares_4',
  f136b: 'performance_intl_shares_4_avg',
  f137a: 'performance_intl_shares_5',
  f137b: 'performance_intl_shares_5_avg',
  f144a: 'performance_capital_stable_fytd',
  f144b: 'performance_capital_stable_fytd_avg',
  f139a: 'performance_capital_stable_1',
  f139b: 'performance_capital_stable_1_avg',
  f140a: 'performance_capital_stable_2',
  f140b: 'performance_capital_stable_2_avg',
  f141a: 'performance_capital_stable_3',
  f141b: 'performance_capital_stable_3_avg',
  f142a: 'performance_capital_stable_4',
  f142b: 'performance_capital_stable_4_avg',
  f143a: 'performance_capital_stable_5',
  f143b: 'performance_capital_stable_5_avg',
  f150a: 'performance_property_fytd',
  f150b: 'performance_property_fytd_avg',
  f145a: 'performance_property_1',
  f145b: 'performance_property_1_avg',
  f146a: 'performance_property_2',
  f146b: 'performance_property_2_avg',
  f147a: 'performance_property_3',
  f147b: 'performance_property_3_avg',
  f148a: 'performance_property_4',
  f148b: 'performance_property_4_avg',
  f149a: 'performance_property_5',
  f149b: 'performance_property_5_avg',
  f156a: 'performance_cash_fytd',
  f156b: 'performance_cash_fytd_avg',
  f151a: 'performance_cash_1',
  f151b: 'performance_cash_1_avg',
  f152a: 'performance_cash_2',
  f152b: 'performance_cash_2_avg',
  f153a: 'performance_cash_3',
  f153b: 'performance_cash_3_avg',
  f154a: 'performance_cash_4',
  f154b: 'performance_cash_4_avg',
  f155a: 'performance_cash_5',
  f155b: 'performance_cash_5_avg',
}

exports.getYears = function (year, month) {
	if (month >= 7) year += 1
	return [
		'fytd',
		year - 1,
		year - 2,
		year - 3,
		year - 4,
		year - 5,
	]
}

exports.ratings = [
  { name: 'MyChoice Platinum', score: 100, abbr: 'platinum', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-choice-platinum-d7lEST7Op.png', type: 'superannuation' },
  { name: 'Platinum', score: 100, abbr: 'platinum', url: '//production-content-assets.ratecity.com.au/20200120/sr-2020-rgb-pen-platinum-DR304rNZ1.png', type: 'pension' },
  { name: 'MyChoice Gold', score: 95, abbr: 'gold', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-choice-gold-X6neouGlQ.png', type: 'superannuation' },
  { name: 'Gold', score: 95, abbr: 'gold', url: '//production-content-assets.ratecity.com.au/20200120/sr-2020-rgb-pen-gold-S_u_OwCzt.png', type: 'pension' },
  { name: 'MyChoice Silver', score: 90, abbr: 'silver', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-choice-silver-7sKacF1La.png', type: 'superannuation' },
  { name: 'Silver', score: 90, abbr: 'silver', url: '//production-content-assets.ratecity.com.au/20200120/sr-2020-rgb-pen-silver-IbaqsV7XI.png', type: 'pension' },
  { name: 'MyChoice Other', score: 85, abbr: 'other', url: '//production-content-assets.ratecity.com.au/20190213123538/SR2019_HiRes_BDR_Choice-Other.jpg', type: 'superannuation' },
  { name: 'Other', score: 85, abbr: 'other', url: '//production-content-assets.ratecity.com.au/20200120/sr-2020-rgb-pen-other-bM7sDH5na.png', type: 'pension' },
  { name: 'MySuper Platinum', score: 100, abbr: 'myplat', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-my-super-platinum-qU9YulQUP.png', type: null },
  { name: 'MySuper Gold', score: 95, abbr: 'mygold', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-my-super-gold-KMOhlV3MY.png', type: null },
  { name: 'MySuper Silver', score: 90, abbr: 'mysilver', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-my-super-silver-YawYCkgFp.png', type: null },
  { name: 'MySuper Other', score: 85, abbr: 'myother', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-my-super-other-EmZNbYvs-.png', type: null },
  { name: '5 Year Platinum Performance', score: 80, abbr: '5yr', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-5-yrpp-hahC-0DCZ.png', type: null },
  { name: '7 Year Platinum Performance', score: 75, abbr: '7yr', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-7-yrpp-0uRv3l1EU.png', type: null },
  { name: '10 Year Platinum Performance', score: 70, abbr: '10yr', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-10-yrpp-2dd7DFSTn.png', type: null },
  { name: '15 Year Platinum Performance', score: 65, abbr: '15yr', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-15-yrpp-FGOllOEww.png', type: null },
  { name: 'Fund of the Year', score: 65, abbr: 'foty', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-foty-DzI5ISx2X.png', type: null },
  { name: 'Super of the Year', score: 55, abbr: 'sfoty', url: '//production-content-assets.ratecity.com.au/20171020104604/super-of-the-year-efe6bcff28f07bbac3ad04bec3e71b7e.jpg', type: null },
  { name: 'Super of the Year Finalist', score: 50, abbr: 'sfoty_f', url: '//production-content-assets.ratecity.com.au/20190213101742/SR2019_HiRes_BDR_Choice-F.jpg', type: null },
  { name: 'Career Fund of the Year', score: 55, abbr: 'cfoty', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-career-S5Vmby8if.png', type: null },
  { name: 'Career Fund of the Year Finalist', score: 50, abbr: 'cfoty_f', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-career-f-Tp_Ht_mCV.png', type: null },
  { name: 'Pension of the Year', score: 50, abbr: 'pfoty', url: '//production-content-assets.ratecity.com.au/20200120/sr-2020-rgb-pension-IZDFALZGZ.png', type: 'pension' },
  { name: 'Pension of the Year Finalist', score: 48, abbr: 'pfoty_f', url: '//production-content-assets.ratecity.com.au/20200120/sr-2020-rgb-pension-f-zVrKK95og.png', type: 'pension' },
  { name: 'Best New Innovation', score: 45, abbr: 'bni', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-bni-dgq4cZzqx.png', type: null },
  { name: 'Best New Innovation Finalist', score: 40, abbr: 'bni_f', url: '//production-content-assets.ratecity.com.au/20200117/sr-2020-rgb-bni-f-wy_orLj8L.png', type: null },
  { name: 'Momentum', score: 39, abbr: 'momentum', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-momentum-SkHObVlc0.png', type: null },
  { name: 'Momentum Finalist', score: 38, abbr: 'momentum_f', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-momentum-f-hYGoHMjhE.png', type: null },
  { name: 'Net Benefit', score: 37, abbr: 'net_benefit', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-net-benefit-LQ1QtYP1j.png', type: null },
  { name: 'Net Benefit Finalist ', score: 36, abbr: 'net_benefit_f', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-net-benefit-f-a6dhB72jc.png', type: null },
  { name: 'Rising Star Award', score: 35, abbr: 'rs', url: '//production-content-assets.ratecity.com.au/20190213124553/SR2019_RS_HiRes_BDR.jpg', type: null },
  { name: 'Rising Star Finalist', score: 30, abbr: 'rs_f', url: '//production-content-assets.ratecity.com.au/20190213124331/SR2019_HiRes_BDR_RS-F.jpg', type: null },
  { name: 'Smooth Ride', score: 29, abbr: 'smooth_ride', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-smooth-ride-70nG3_pga.png', type: null },
  { name: 'Smooth Ride Finalist', score: 28, abbr: 'smooth_ride_f', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-smooth-ride-f-CkRfMJ2ud.png', type: null },
  { name: 'Fast Mover', score: 16, abbr: 'fm', url: '//production-content-assets.ratecity.com.au/20180814171925/SR2018_FM_Hi-Res_c.jpg', type: null },
  { name: 'SR50 Growth Index', score: 20, abbr: '50gr', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-sr-50-best-grow-wxVJBMlY8.png', type: null },
  { name: 'SR50 Balanced Index', score: 15, abbr: '50bal', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-sr-50-best-bal-OOgjJt67V.png', type: null },
  { name: 'SR50 Capital Stable Index', score: 14, abbr: '50cap', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-sr-50-best-cap-aNtpE-PKx.png', type: null },
  { name: 'SR50 Cash Index', score: 13, abbr: '50cash', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-sr-50-best-cash-eRL6JTwL6.png', type: null },
  { name: 'SR50 Australian Shares Index', score: 12, abbr: '50aust', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-sr-50-best-aust-wdxF2eY4l.png', type: null },
  { name: 'SR50 International Shares Index', score: 11, abbr: '50int', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-sr-50-best-int-r_u6K4a-L.png', type: null },
  { name: 'Infinity Award', score: 10, abbr: 'infinity', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-infin-ptCgDkMuF.png', type: null },
  { name: 'Infinity Recognised', score: 9, abbr: 'infinity_r', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-infin-rec-WCywxnpTw.png', type: null },
  { name: 'Choice Super of the Year', score: 60, abbr: 'csoty', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-choice-TE8q264Md.png', type: null },
  { name: 'Choice Super of the Year Finalist', abbr: 'csoty_f', score: 55, url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-choice-f-IqiESp-ou.png', type: null },
  { name: 'MySuper of the Year', score: 53, abbr: 'msoty', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-my-super-e3ZkN-e7G.png', type: null },
  { name: 'MySuper of the Year Finalist', score: 51, abbr: 'msoty_f', url: '//production-content-assets.ratecity.com.au/20200119/sr-2020-rgb-my-super-f-bD0rIMOVY.png', type: null },
]

exports.segments = [
  { name: 'MySuper', regx: new RegExp('mysuper$', 'i') },
  { name: 'Personal', regx: new RegExp('(government|personal)$', 'i') },
  { name: 'Public Offer', regx: new RegExp('public offer$', 'i') },
  { name: 'Non Public Offer', regx: new RegExp('non public offer$', 'i') },
  { name: 'Account-based Pension', regx: new RegExp('pension$', 'i') },
  { name: 'Corporate', regx: new RegExp('corporate$', 'i') },
]

exports.purposes = [
  { name: 'Personal', regx: new RegExp('(industry-(mysuper|personal|public offer)|master trust-(mysuper|personal))', 'i') },
  { name: 'Other', regx: new RegExp('(corporate($|-mysuper|-personal)|government($|-mysuper|-personal)|industry-non public offer|master trust-corporate)', 'i') },
]

exports.options = [
	'balanced', 'high_growth', 'conservative_balance', 'secure', 'diversified', 'growth',
	'aus_shares', 'intl_shares', 'capital_stable', 'property', 'cash',
]
