module.exports = {
	'Bad Credit': { collection: 'GenericProduct', findClause: { vertical: 'bad-credit' }, slug: 'bad-credit', salesforceVertical: 'Bad Credit' },
	'Car Insurance': { collection: 'GenericProduct', findClause: { vertical: 'car-insurance' }, slug: 'car-insurance', salesforceVertical: 'Car Insurance' },
	'Display': { collection: 'GenericProduct', findClause: { vertical: 'display' }, slug: 'display', salesforceVertical: 'Display' },
	'Foreign Exchange': { collection: 'GenericProduct', findClause: {vertical: 'foreign-exchange'}, slug: 'foreign-exchange', salesforceVertical: 'Foreign Exchange' },
	'Health Insurance': { collection: 'GenericProduct', findClause: {vertical: 'health-insurance'}, slug: 'health-insurance', salesforceVertical: 'Health Insurance' },
	'Health Product': { collection: 'GenericProduct', findClause: { vertical: 'health-product' }, slug: 'health-product', salesforceVertical: 'Health Product' },
	'Home Insurance': { collection: 'GenericProduct', findClause: { vertical: 'home-insurance' }, slug: 'home-insurance', salesforceVertical: 'Home Insurance' },
	'Income Protection Insurance': { collection: 'GenericProduct', findClause: { vertical: 'income-protection-insurance' }, slug: 'income-protection-insurance', salesforceVertical: 'Income Protection Insurance' },
	'Life Insurance': { collection: 'GenericProduct', findClause: { vertical: 'life-insurance' }, slug: 'life-insurance', salesforceVertical: 'Life Insurance' },
	'Managed Funds': { collection: 'GenericProduct', findClause: {vertical: 'managed-funds'}, slug: 'managed-funds', salesforceVertical: 'Managed Funds' },
	'Margin Loans': { collection: 'GenericProduct', findClause: { vertical: 'margin-loans' }, slug: 'margin-loans', salesforceVertical: 'Margin Loans' },
	'Mortgage Insurance': { collection: 'GenericProduct', findClause: { vertical: 'mortgage-insurance' }, slug: 'mortgage-insurance', salesforceVertical: 'Mortgage Insurance' },
	'Online Share Trading': { collection: 'GenericProduct', findClause: { vertical: 'online-trading' }, slug: 'online-trading', salesforceVertical: 'Online Share Trading' },
	'Travel Cards': { collection: 'GenericProduct', findClause: {vertical: 'travel-cards'}, slug: 'travel-cards', salesforceVertical: 'Travel Cards' },
}
